
apiVersion: v1
kind: Service
metadata:
  name: operator # Please do not change this value
  labels:
    name: minio-operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
  namespace: ns-minio
spec:
  type: ClusterIP
  ports:
    - port: 4221
      name: http
  selector:
    name: minio-operator
    operator: leader
---
apiVersion: v1
kind: Service
metadata:
  name: sts # Please do not change this value
  labels:
    name: minio-operator
  namespace: ns-minio
spec:
  type: ClusterIP
  ports:
    - port: 4223
      targetPort: 4223
      name: https
  selector:
    name: minio-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: ns-minio
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: minio-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: minio-operator
        app.kubernetes.io/instance: minio-operator
        app.kubernetes.io/name: operator
    spec:
      serviceAccountName: minio-operator
      containers:
        - name: minio-operator
          image: minio/operator:v5.0.11
          imagePullPolicy: IfNotPresent
          args:
            - controller
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 500Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          env:
            - name: MINIO_CONSOLE_TLS_ENABLE
              value: "off"
            - name: OPERATOR_STS_ENABLED
              value: "off"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minio-operator
              topologyKey: kubernetes.io/hostname